-- Create the community gallery table
create table if not exists community_gallery (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  media_url text not null,
  thumbnail_url text,
  media_type text default 'image' check (media_type in ('image', 'video')),
  caption text,
  author text,
  is_visible boolean default true,
  display_order integer default 0
);

-- Enable RLS
alter table community_gallery enable row level security;

-- Policies
create policy "Gallery is viewable by everyone" on community_gallery for select using ( is_visible = true );
create policy "Gallery is manageable by admins" on community_gallery for all using ( true );

-- Insert some sample data (placeholder URLs)
insert into community_gallery (media_url, media_type, caption, author, display_order)
values
  ('https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c', 'image', 'Petit ours voyageur', 'Marie P.', 10),
  ('https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4', 'image', 'Premier anniversaire magique', 'Pierre L.', 20),
  ('https://images.unsplash.com/photo-1566004100631-35d015d6a491', 'image', 'Coin lecture enchanté', 'Sophie D.', 30);
