-- Create reviews table
create table if not exists reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  rating integer check (rating >= 1 and rating <= 5),
  text text not null,
  avatar text,
  is_visible boolean default true,
  display_order integer default 0
);

-- Enable RLS
alter table reviews enable row level security;

-- Policies
create policy "Reviews are viewable by everyone"
  on reviews for select
  using ( is_visible = true );

create policy "Anyone can insert reviews"
  on reviews for insert
  with check ( true );

create policy "Anyone can update reviews"
  on reviews for update
  using ( true );

create policy "Anyone can delete reviews"
  on reviews for delete
  using ( true );

-- Insert initial sample data
insert into reviews (name, role, rating, text, is_visible, display_order)
values
  ('Marie P.', 'Maman comblée', 5, 'Les jouets sont d''une qualité incroyable. Ma fille ne quitte plus son ours !', true, 10),
  ('Pierre L.', 'Papa de 2 enfants', 5, 'Livraison super rapide et emballage soigné. Parfait pour les cadeaux.', true, 20),
  ('Sophie D.', 'Enseignante', 4, 'J''adore la sélection de livres, on y trouve des perles rares.', true, 30),
  ('Camille R.', 'Cliente fidèle', 5, 'Le service client est adorable et très réactif. Merci pour tout !', true, 40);
