-- Create the menu_items table
create table if not exists menu_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  label text not null,
  path text,
  display_order integer default 0,
  type text not null, -- 'root', 'section', 'link'
  parent_id bigint references menu_items(id) on delete cascade,
  is_active boolean default true
);

-- Enable RLS
alter table menu_items enable row level security;

-- Policies (Public access for V3 Demo - Secure this later!)
create policy "Anyone can read menu items"
  on menu_items for select
  using ( true );

create policy "Anyone can insert menu items"
  on menu_items for insert
  with check ( true );

create policy "Anyone can update menu items"
  on menu_items for update
  using ( true );

create policy "Anyone can delete menu items"
  on menu_items for delete
  using ( true );

-- Insert default categories to verify it works
insert into menu_items (label, path, display_order, type, parent_id)
values 
('Livres', '/category/livres', 10, 'root', null),
('Jouets', '/category/jouets', 20, 'root', null),
('Déco', '/category/deco', 30, 'root', null);
