-- Create a table for products
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  price numeric not null,
  image text,
  category text,
  subcategory text,
  stock integer default 0,
  is_new boolean default false
);

-- Enable Row Level Security (optional but recommended)
alter table products enable row level security;

-- Create a policy that allows anyone to read products (public access)
create policy "Products are viewable by everyone"
  on products for select
  using ( true );

-- Create a policy that allows anyone to insert products (for admin demo purposes - secure this in prod!)
create policy "Anyone can insert products"
  on products for insert
  with check ( true );

-- Create a policy that allows anyone to update products
create policy "Anyone can update products"
  on products for update
  using ( true );

-- Insert some sample data
insert into products (title, price, category, subcategory, image, stock, is_new)
values
  ('Livre - Le Petit Prince', 15.90, 'Livres', 'Romans', 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800', 50, false),
  ('Puzzle Bois 500p', 24.99, 'Jouets', 'Jeux de société', 'https://images.unsplash.com/photo-1587654780291-39c940483719?auto=format&fit=crop&q=80&w=800', 30, true),
  ('Ours en Peluche', 19.50, 'Jouets', 'Éveil', 'https://images.unsplash.com/photo-1559454403-b8fb87521bc7?auto=format&fit=crop&q=80&w=800', 100, false);

-- UPDATE: Add SEO fields
alter table products add column if not exists image_alt text;

-- STORAGE SETUP (Requires manually running in SQL Editor if bucket doesn't exist)
-- Note: Creating buckets via SQL is possible if you have permissions, otherwise do it in Dashboard > Storage > New Bucket 'product-images' (Public)

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

create policy "Images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'product-images' );

create policy "Anyone can upload images"
  on storage.objects for insert
  with check ( bucket_id = 'product-images' );

-- BLOG POSTS TABLE
create table posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  excerpt text,
  content text,
  image text,
  date text, -- Manual date string to keep it simple for now, or use created_at
  read_time text,
  author text default 'Elya',
  image_alt text
);

alter table posts enable row level security;

create policy "Posts are viewable by everyone"
  on posts for select
  using ( true );

create policy "Anyone can insert posts"
  on posts for insert
  with check ( true );

create policy "Anyone can update posts"
  on posts for update
  using ( true );

create policy "Anyone can delete posts"
  on posts for delete
  using ( true );

-- BLOG IMAGES BUCKET
insert into storage.buckets (id, name, public)
values ('blog-images', 'blog-images', true)
on conflict (id) do nothing;

create policy "Blog images are publicly accessible"
  on storage.objects for select
  using ( bucket_id = 'blog-images' );

create policy "Anyone can upload blog images"
  on storage.objects for insert
  with check ( bucket_id = 'blog-images' );

-- UPDATE: Add SEO fields for posts
alter table posts add column if not exists image_alt text;

-- UPDATE: Add aspect_ratio to products
alter table products add column if not exists aspect_ratio text default 'portrait';

-- UPDATE: Add images (JSONB) to products
alter table products add column if not exists images jsonb default '[]'::jsonb;
